[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/survey"
  to = "https://www.surveygizmo.com/s3/5220252/c97ec149ec04"
  status = 301
  force = true

  from = "/fairytaleplayers"
  to = "/programs/fairytale-players"
  status = 301
  force = true